services:
  mqtt:
    image: eclipse-mosquitto:2.0.15-openssl
    container_name: mqtt
    user: ${PUID:?}:${GUID:?}
    restart: unless-stopped
    healthcheck:
      test: ping -c 1 www.google.com || exit 1
      interval: 30s
      timeout: 10s
      retries: 5
    env_file:
      - .env
    labels:
      - traefik.enable=true
      - traefik.tcp.routers.mqtt.rule=HostSNI(`mqtt.${TRAEFIK_DOMAIN:?}`)
      - traefik.tcp.routers.mqtt.entrypoints=mqtt
      - traefik.tcp.routers.mqtt.tls=true
      - traefik.tcp.routers.mqtt.tls.certresolver=cloudflare
      - traefik.tcp.services.mqtt.loadBalancer.server.port=1883
    networks:
      - traefik
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data/:/mosquitto/data/
      - ./files/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - ./files/mosquitto.log:/mosquitto/log/mosquitto.log
      - ./files/mosquitto.passwd:/mosquitto/config/mosquitto.passwd

networks:
  traefik:
    external: true